
String baseImage = "base-python"

pipeline {

   agent any

   stages {
      stage('Hello') {
         steps {
            echo 'Hello World Test'
         }
      }
      stage('ls') {
         steps {
             script {
                 print(GIT_BRANCH)
             }
         }
      }
   }
}

private String getDockerParams() {
    dockerParameters = [
            "-v", "$workspace:/usr/src/app"
    ]

    return "${dockerParameters.join(' ')}"
}